---
name: Lint code

on:
  push:
    branches-ignore: [test]
  pull_request:
    branches-ignore: [test]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install codespell
        run: pip install codespell tomli

      - name: Run codespell
        run: codespell

      - name: Install markdown-lint-check
        run: npm install -g markdown-link-check

      - name: Run markdown-lint-check
        run: find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check -a 0 -p -v -r
